### ISSUE TITLE
Please add ajv to peer dependencies

### ISSUE THREAD

**Issue by BlackGlory** [ajv-validator/ajv-formats#13]
TypeScript projects that use `ajv` and `ajv-formats` may have compilation errors after every upgrade. This is because a different version of `ajv` is installed under `node_modules/ajv-formats/node_modules`, the only way to solve this problem is to add `ajv` to the peer dependency of `ajv-formats`.

**Comment by drtyh2o** [comment]
> TypeScript projects that use `ajv` and `ajv-formats` may have compilation errors after every upgrade. This is because a different version of `ajv` is installed under `node_modules/ajv-formats/node_modules`, the only way to solve this problem is to add `ajv` to the peer dependency of `ajv-formats`.

Also, if you use `yarn workspaces` and `ESLint` which also has a dependency on `ajv` then you can get errors even when using the same version (we recently switched to [pnpm](https://pnpm.js.org/) because of this), but I ran into this issue again when attempting to upgrade to `ajv 7.1.1` just now.

`error TS2345: Argument of type 'import("/myrepo/node_modules/.pnpm/ajv@7.1.1/node_modules/ajv/dist/ajv").default' is not assignable to parameter of type 'import("/myrepo/node_modules/.pnpm/ajv@7.0.4/node_modules/ajv/dist/core").default'.
  Types of property 'opts' are incompatible
`

**Comment by epoberezkin** [comment]
merged
